// +build codegen

package manifest

import (
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"os"
)

const header = `// Code generated by schema_codegen.go. DO NOT EDIT.

package manifest
`

func main() {
	f, err := os.OpenFile("schema_data.go", os.O_CREATE|os.O_RDWR, 0755)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	_, err = f.WriteString(header)
	if err != nil {
		log.Fatal(err)
	}

	err = writeVarFromFile(f, "parametersSchema", "schemas/parameterfile.yml")
	if err != nil {
		log.Fatal(err)
	}

	err = writeVarFromFile(f, "manifestSchema", "schemas/manifest.yml")
	if err != nil {
		log.Fatal(err)
	}

	_, err = f.WriteString("\n")
	if err != nil {
		log.Fatal(err)
	}
}

func writeVarFromFile(w io.Writer, varname string, filename string) (err error) {
	_, err = fmt.Fprintf(w, "var %s = []byte(`\n", varname)
	if err != nil {
		return
	}

	data, err := ioutil.ReadFile(filename)
	if err != nil {
		return
	}

	_, err = w.Write(data)
	if err != nil {
		return
	}

	_, err = fmt.Fprint(w, "`)\n")
	if err != nil {
		return
	}

	return
}
