version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.5

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go test -i ./...
      - run: go test ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  release:
    docker:
      - image: circleci/golang:1.12.5

    steps:
      - checkout
      - run: go run mage.go build:all
      - run: .circleci/github-release.sh

workflows:
  version: 2
  build_and_release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+(-[ab][0-9]+)?$/
