version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.6

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go test ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  release:
    docker:
      - image: circleci/golang:1.12.6

    steps:
      - checkout
      - restore_cache:
        keys:
          - go-mod-v1-{{ checksum "go.sum" }}
      - run: make
      - run: .circleci/github-release.sh

workflows:
  version: 2
  build_and_release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

